# Generated by Django 5.0.6 on 2024-06-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0002_alter_records_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='records',
            name='state',
            field=models.CharField(max_length=10),
        ),
    ]
